# Generated by Django 2.2.7 on 2019-12-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('squaremeters', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
